server:
  port: 8086
spring:
  rabbitmq:
    host: 192.168.79.129
    username: fjc
    password: fjc
    virtual-host: /fjc
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: http://192.168.79.129:9200