server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
gmall:
  jwt:
    pubKeyPath: E:\\workspaceIDEA\\project\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: E:\\workspaceIDEA\\project\\tmp\\rsa\\rsa.pri # 私钥地址
    secret: sf3423jsdf#3$@FDS32
    expire: 3600 # 过期时间,单位秒
    cookieName: GMALL_TOKEN